#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
keyring_index:
    path: /
    controller: App\Controller\MainController::index

app_dhcp_add:
    path: /modifyuser
    controller: App\Controller\UserController::modifyUser

app_dhcp_vivs_errormessage:
    path: /errormsg
    controller: App\Controller\KeyringController::errormsg

app_dhcp_vivs_savetrousseau:
    path: /saveKey
    controller: App\Controller\KeyringController::saveKey

app_dhcp_vivs_listtrousseau:
    path: /listageKey
    controller: App\Controller\KeyringController::listKey

app_vivs_modif_pret:
    path: /modifyPret
    controller: App\Controller\KeyringController::modifyPret



app_vivs_delete_pret:
    path: /deletePret
    controller: App\Controller\KeyringController:deletePret

app_vivs_ajax_list_trousseau:
    path: /listKeyAjax
    controller: App\Controller\KeyringController:listKeyAjax

app_vivs_ajax_list_trousseau_free:
    path: /listFreeKeyAjax
    controller: App\Controller\KeyringController:listFreeKeyAjax

app_vivs_list_pret:
    path: /listagePret
    controller: App\Controller\KeyringController:listLend

app_vivs_add_pret:
    path: /addPret
    controller: App\Controller\KeyringController::addPret

app_vivs_createUser:
    path: /adduser
    controller: App\Controller\createUser::createUser

app_vivs_login_page:
    path: /login
    controller: app\Controller\MainController::MainController


app_vivs_expiration:
    path: /expiration
    controller: app\Controller\KeyringController::listExpiration

keyring_user_autoComplete:
    path: /searchUserAjax
    controller: App\Controller\UserController::autoComplete

chart_key_site:
    path: /listTrousseauPerSitesAjax
    controller: App\Controller\KeyringController:listTrousseauPerSitesAjax

chart_key_state:
    path: /listTrousseauPerStateAjax
    controller: App\Controller\KeyringController:listTrousseauPerStateAjax

user_list:
    path: /listusers
    controller: app\Controller\UserController::listUser

user_new:
    path: /user/new
    controller: App\Controller\UserController::createUser

user_view:
    path: /user/view
    controller: App\Controller\UserController::view

user_view_pdf:
    path: /user/view/pdf
    controller: App\Controller\UserController::viewPdf

user_add_ajax:
    path: /user/add/ajax
    controller: App\Controller\UserController::addUserAjax
        
user_modify:
    path: /user/modify
    controller: App\Controller\UserController::modifyUser

user_profil:
    path: /user/profil
    controller: App\Controller\UserController::profil

user_replaceCreatorKeys:
    path: /user/replaceCK
    controller: App\Controller\UserController::replaceCreatorKey

key_new:
    path: /key/new
    controller: App\Controller\KeyringController::newKey

key_list:
    path: /key/list
    controller: App\Controller\KeyringController::listKey

key_list_ajax:
    path: /key/ajax/list
    controller: App\Controller\KeyringController::listKeysAjax

key_modify:
    path: /key/modify
    controller: App\Controller\KeyringController::modifyKey

key_delete:
    path: /deleteKey
    controller: App\Controller\KeyringController:deleteKey

key_view:
    path: /key/view
    controller: App\Controller\KeyringController::viewKey

lend_modify:
    path: /lend/modify
    controller: App\Controller\KeyringController::modifyPret

lend_new:
    path: /lend/new
    controller: App\Controller\KeyringController::newLend

lend_list:
    path: /lend/list
    controller: App\Controller\KeyringController::listLend

lend_history:
    path: /lend/history
    controller: App\Controller\KeyringController::historyLend

param_list_ajax:
    path: /param/list/ajax
    controller: App\Controller\ParamController::getParamsAjax

param_list:
    path: /param/list/
    controller: App\Controller\ParamController::list

param_modify:
    path: /param/modify/
    controller: App\Controller\ParamController::modify

param_new:
    path: /param/new/
    controller: App\Controller\ParamController::new

param_save:
    path: /param/save/
    controller: App\Controller\ParamController::save

param_delete:
    path: /param/delete/
    controller: App\Controller\ParamController::delete

pdf_key_list:
    path: /key/list/pdf
    controller: App\Controller\KeyringController::pdfAction

pdf_lend_view:
    path: /lend/view/pdf
    controller: App\Controller\KeyringController::lendPdf
    
excel_lend:
    path: /lend/excel
    controller: App\Controller\KeyringController::excel
